stages:
    - prepare
    - build
    - test
    - deploy
    - pages

cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target/
        - cargo/
    policy: pull-push

rust-latest:
    stage: prepare
    image: rust:latest
    cache:
        <<: *global_cache
        policy: push
    script:
        - cargo build --verbose
        - cargo test --verbose

build_docker_image:
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    stage: build
    needs: [rust-latest]
    when: on_success
    only:
        - master
    script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

lint-code:
    stage: test
    needs: [rust-latest]
    when: on_success
    cache:
        <<: *global_cache
        policy: pull
    script:
        - rustup component add clippy
        - cargo clippy -- -D warnings

format-code:
    stage: test
    needs: [rust-latest]
    when: on_success
    cache:
        <<: *global_cache
        policy: pull
    script:
        - rustup component add rustfmt
        - cargo fmt -- --check

audit-code:
    stage: test
    needs: [rust-latest]
    when: on_success
    cache:
        <<: *global_cache
        policy: pull
    script:
        - cargo install cargo-audit
        - cargo audit

deploy_to_k8s:
    image: bitnami/kubectl:latest
    stage: deploy
    needs: [build_docker_image]
    when: on_success
    only:
        - master
    script:
        - kubectl apply -f k8s/deployment.yaml -n $CI_REGISTRY_IMAGE

deploy_to_pages:
    image: rustdocker/rust:latest
    needs: [rust-latest]
    when: on_success
    stage: pages
    only:
        - master
    script:
        - cargo doc
        - rm -rf public
        - mkdir public
        - cp -R target/doc/* public
    artifacts:
        paths:
            - public
