[package]
name = "zorius"
version = "0.1.0"
authors = ["ceox"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9"
bson = "0.14.0"

actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"