[package]
authors = ["ceox <mizuo@pm.me>"]
edition = "2018"
name = "zorius"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = "0.2"
# with 0.9.1 mongodb uses async resolver. this prevents it from running with actix_rt. because it spawns a runtime in a runtime
bson = "1.1"
mongodb = "1.1"
ron = "0.6"

uuid = {version = "0.8", features = ["serde", "v4"]}

dotenv = "0.15"
dotenv_codegen = "0.15"

actix-cors = "0.3"
actix-files = "0.3"
actix-rt = "1.1"
actix-web = {version = "3.0", features = ["rustls"]}
rustls = "0.18"

env_logger = "0.7"
juniper = {git = "https://github.com/graphql-rust/juniper.git", features = ["chrono", "uuid", "url", "bson"]}
juniper_actix = {git = "https://github.com/graphql-rust/juniper.git"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

chrono = {version = "0.4", features = ["serde"]}
