[package]
authors = ["ceox <mizuo@pm.me>"]
edition = "2018"
name = "zorius"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5"
actix-files = "0.5"
actix-multipart = "0.3"
actix-ratelimit = "0.3"
actix-rt = "1.1"
actix-web = {version = "3.3", features = ["rustls"]}
async-graphql = {version = "2.4", features = ["bson", "multipart", "chrono"]}
async-graphql-actix-web = "2.4"
async-trait = "0.1"
bson = "1.1"
chrono = {version = "0.4", features = ["serde"]}
dotenv = "0.15"
dotenv_codegen = "0.15"
env_logger = "0.8"
futures = "0.3"
jsonwebtoken = "7"
lazy_static = "1.4"
log = "0.4"
mongodb = "1.1"
pwhash = "1.0"
ron = "0.6"
rustls = "0.18.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.4"
tokio = {version = "1.0", features = ["fs", "io-util", "rt", "time"]}
tokio-stream = "0.1"
url = "2.2"
uuid = {version = "0.8", features = ["serde", "v4"]}
