[package]
authors = ["ceox <mizuo@pm.me>"]
edition = "2018"
name = "zorius"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5"
actix-files = "0.5"
actix-multipart = "0.3"
actix-ratelimit = {version = "0.3", default-features = false, features = ["memory"]}
actix-web = {version = "3.3", features = ["rustls"]}
askama = "0.10.5"
async-graphql = {version = "2.8", features = ["bson", "chrono", "dataloader"]}
async-graphql-actix-web = "2.8"
async-trait = "0.1"
bson = "1.1"
chrono = {version = "0.4", features = ["serde"]}
config = "0.11"
dotenv = "0.15"
dotenv_codegen = "0.15"
env_logger = "0.8"
futures = "0.3"
jsonwebtoken = "7"
lazy_static = "1.4"
lettre = "0.9"
lettre_email = "0.9"
log = "0.4"
mongodb = "1.2"
pwhash = "1.0"
ron = "0.6"
rustls = "0.18.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.4"
tokio = {version = "0.2"}
url = "2.2"
uuid = {version = "0.8", features = ["v4"]}
