# which domain to use to generate urls for files
domain = "localhost"
# log level to use. Available Options: "trace", "debug", "info", "error", "none"
log_level = "info"
# enable registration
registration_enabled = true
# secete key for generating password hashes
# choose a long and complex (more than 128 character) key
secret_key = ""
# how long should the authetication token be valid
token_lifetime = 86400

[web]
# path to the ssl cert
cert_path = ""
# should ssl be enabled
# if zorius is used behind a reverse proxy set this to false
enable_ssl = false
# ip zorius should listen to
ip = "127.0.0.1"
# path to the ssl private key
key_path = ""
# log format zorius should use
# available options can be found here: https://actix.rs/actix-web/actix_web/middleware/struct.Logger.html
log_format = "IP:%a REQUEST:\"%r\" STATUS: %s DURATION: %Dms X-REQUEST-ID:%{x-request-id}o"
# port zorius should listen
port = 8080

[db]
# database dns or ip
host = "localhost"
# database port
port = 5432
# database name
name = "zorius"
# username for the database
username = "zorius"
# password for the database user
password = "zorius"

[mailer]
# where should zorius send emails to whena status of a merchandise changes
merchandise_email_send_to = ""
# should zorius send emails
enable_mailer = false
# smtp server host/address
smtp_address = ""
# smtp server password
smtp_password = ""
# smtp server username
smtp_username = ""

