debug = true
domain = "localhost"
registration_enabled = false
secret_key = ""
token_lifetime = 86400

[web]
cert_path = "cert.pem"
enable_ssl = true
ip = "127.0.0.1"
key_path = "key.pem"
log_format = "IP:%a REQUEST:\"%r\" STATUS: %s DURATION: %Dms X-REQUEST-ID:%{x-request-id}o"
port = 443

[db]
app_name = "zorius"
name = "zorius"
password = ""
server = ""
username = "zorius"

[mailer]
email_send_to = ""
enable_mailer = false
smtp_address = ""
smtp_password = ""
smtp_username = ""
