debug = true
domain = "localhost"
registration_enabled = true
token_lifetime = 86400

[web]
cert_path = "cert.pem"
enable_ssl = true
ip = "127.0.0.1"
key_path = "key.pem"
log_format = "IP:%a DATETIME:%t REQUEST:\"%r\" STATUS: %s DURATION: %D X-REQUEST-ID:%{x-request-id}o"
port = 443

[db]
app_name = "zorius"
name = "zorius"
password = ""
server_domain = ""
username = "zorius"
